baseURL = "https://sys4dm1npub.github.io/"
languageCode = "en-us"
title = "Sys4dm1nPub"
theme = "hugo-vitae"
paginate = 5

copyright = "© Copyleft Sys4dm1nPub | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "https://disqus.com/sys4dm1npub/"

[taxonomies]
	tag = "tags"
	series = "series"
        author = "autores"

[params]
	subtitle = "Bem-vindo(a) ao nosso blog! Nosso foco é conteúdo com qualidade."

	# Optional 80x80 avatar image.
	avatar = "/img/choice.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.

[params.comments]
enable=true

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Sobre"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/sys4dm1npub"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
